# Generated by Django 5.2.1 on 2025-05-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_savednetwork_delete_artistnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='savednetwork',
            name='path',
            field=models.JSONField(default=list),
        ),
    ]
